import { Outlet, Link } from "react-router-dom";
import './Layout.css';
const Layout = () => {

    const myStyle = {
        nav: {

        },
        ul: {
            display: 'flex',
            listStyle: 'none'
        },
        li: {
            padding: "10px",
            backgroundColor: "orange",
            color: "white",
            marginRight: '10px'
        }
    };

    return (
        <>
            <nav className="mainMenu">
                <ul >

                    
                    <li><Link to="/">Home</Link></li>
                    <li >
                        <Link to="/">Home</Link>
                    </li>
                    <li >
                        <Link to="/blogs">Blogs</Link>
                    </li>
                    <li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li><li >
                        <Link to="/contact">Contact</Link>
                    </li>
                </ul>
            </nav>

            <Outlet />
        </>
    )
};

export default Layout;